### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by sebinsua** [sebinsua/redux-api-helpers#1]
Effectively, I think you should just be able to define action types and in the majority of cases have further actions, reducers and sagas generated off these. Only rarely should you need to provide manual transformation functions. 

See: http://redux.js.org/docs/recipes/ReducingBoilerplate.html#userinfojs
See: https://github.com/afitiskin/redux-saga-actions
## TODO
- [ ] Break up concerns, and handle one problem at a time within a separate repo.
- [ ] See:
  - https://github.com/micro-js/handle-actions 
  - https://github.com/micro-js/create-action
  - https://github.com/felixmc/redux-actions-magic
  - https://github.com/layflags/action-types
- [ ] Actions should send their `status`, and this should be placed into the state-tree.
- [ ] Rename `ERROR` to `FAIL`.
- [ ] Create action types from a namespace and an action name. Define the action types as `${namespaceName}/${actionName}`. For example, `grids/FETCH_GRIDS` and `grids/FETCH_GRIDS_SUCCESS`. The benefit of this is that you can know the mapping of `namespaceName` to `actionName`, and later on with a `reducer` the `namespaceName` could help describe the `reducerKey` to store data within.
- [ ] Use `redux-actions#createAction` to create the action creators from the action types. Action creators should take only a single `payload` object argument.
- [ ] `createApiActions` should produce three actions.
- [ ] `createApiReducer` should handle three actions; by default there should be no transformations (the `identity` function). We should be able to generate the reducer from a `namespaceName` and its related actions. Behind the scenes we can use `redux-machine#createMachine` and `redux-actions#handleAction` to automatically define reducers which handle storing the responses of the API actions described above.
- [ ] Rewrite `redux-saga-helpers` so that it can use some of this this logic, too. Actions which create sagas should use a `createApiSaga` which handles producing `${actionName}_FAIL` and `${actionName}_SUCCESS` actions.
### Function calls, dispatches and `yield call` as semantic sugar

``` js
// normal javascript function ‘call'
// only grids.callFn needs to be implemented.
const responseOfGridsCallFn = grids.callFn(…args)

// redux action ‘dispatch’
// gridActions.action, and gridReducers.handleAction need to be implemented 
dispatch(gridActions.action(…args))
const responseOfGridsActionDispatch = redux.getStore().grids

// saga call instruction ‘yield’
// gridActions.actionSuccess, gridActions.actionFail need to be implemented
const responseOfFetchGrid = yield call(api.fetchGrid, …args)
```

These are all boilerplate to handle intricacies around the same problem: passing an input to a function to get some output. If you `call` it is synchronous and the data response is returned locally. If you `dispatch` it is synchronous but placed on a queue, and the data response can be placed into a global state tree which may feed multiple components. If you `yield` it may be asynchronous and the data response is returned locally.

A function call has very little boilerplate. A dispatch call seems to require way too much boilerplate by default. A yield can require boilerplate, due to using dispatch itself.

What is funny/bad is that they are all effectively the same thing: `fn: input -> output`; just with extra rules around them and varying degrees of crap you might need to write.
